//Dependencies
import type { NextPage } from "next";
import Head from "next/head";

//Components
import HeroMain from "@components/HeroMain";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroMain />
    </>
  );
};

export default Home;
